Relax JVM version check in startup scripts
Allow VM that has a version string different from 1.8 to allow to start
neo4j on latest JDK.
The restriction that will not allow starting neo4j on older JVM version
is still in place.
Also, update scripts to indicate that they are actually generated based
on the template. Align template and fixes that were only applied to scripts.
Add tests that verify windows startup scripts.

diff --git a/private/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j b/private/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j
--- a/private/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j
+++ b/private/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j
@@ -3,6 +3,7 @@
 # Network Engine for Objects in Lund AB [http://neotechnology.com]
 # This file is a commercial add-on to Neo4j Enterprise Edition.
 #
+
 # Callers may provide the following environment variables to customize this script:
 #  * JAVA_HOME
 #  * JAVA_CMD
@@ -10,6 +11,9 @@
 #  * NEO4J_CONF
 #  * NEO4J_START_WAIT
 
+#############################################################
+#      File content is generated based on .m4 template      #
+#############################################################
 
 set -o errexit -o nounset -o pipefail
 [[ "${TRACE:-}" ]] && set -o xtrace
@@ -70,16 +74,23 @@ check_java() {
   [[ -n "${JAVA_MEMORY_OPTS:-}" ]] && version_command+=("${JAVA_MEMORY_OPTS[@]}")
 
   JAVA_VERSION=$("${version_command[@]}" 2>&1 | awk -F '"' '/version/ {print $2}')
-  if [[ "${JAVA_VERSION}" < "1.8" ]]; then
-    echo "ERROR! Neo4j cannot be started using java version ${JAVA_VERSION}. "
-    _show_java_help
-    exit 1
+  if [[ $JAVA_VERSION = "1."* ]]; then
+    if [[ "${JAVA_VERSION}" < "1.8" ]]; then
+      echo "ERROR! Neo4j cannot be started using java version ${JAVA_VERSION}. "
+      _show_java_help
+      exit 1
+    fi
+    if ! ("${version_command[@]}" 2>&1 | egrep -q "(Java HotSpot\\(TM\\)|OpenJDK|IBM) (64-Bit Server|Server|Client|J9) VM"); then
+      unsupported_runtime_warning
+    fi
+  else
+      unsupported_runtime_warning
   fi
+}
 
-  if ! ("${version_command[@]}" 2>&1 | egrep -q "(Java HotSpot\\(TM\\)|OpenJDK|IBM) (64-Bit Server|Server|Client|J9) VM"); then
+unsupported_runtime_warning() {
     echo "WARNING! You are using an unsupported Java runtime. "
     _show_java_help
-  fi
 }
 
 # Resolve a path relative to $NEO4J_HOME.  Don't resolve if
